VPN request policies
OHS-Hosting-Infrastructure/infrastructure pull request #13
Opened 2021-05-19 14:41 UTC by rahearn

#6 

This VPN access policy includes instructions for more securely generating private keys locally.

Changes proposed in this pull request:

- New VPN clients generate Certificate Signing Requests instead of VPN server generating all files

2021-05-19 14:50 UTC, rahearn commented
@jduss4 is going to make edits to this process as needed as she sets up her own VPN access

2021-05-20 19:01 UTC, jduss4 commented on docs/runbooks/vpn-access-requests.md
> +    - `eclkc_centos_id_rsa` (may be sent separately and named differently)
Good point.  I suppose my instinct is to have documentation that's accurate now and then update / replace it when that's no longer the case, but it's a pretty minor piece so either way is okay with me.  I assume if we removed this, then we'd also want to take out the`-i` flag from `ssh` below, right?

2021-05-20 19:57 UTC, rahearn commented on docs/runbooks/vpn-access-requests.md
> +    - `eclkc_centos_id_rsa` (may be sent separately and named differently)
One thing we could do in the short term is add each person's public ssh key to the centos user on one of the machines, and then to SSH into the system you log into that machine first, and then can use the centos private key from there to other machines? Still not very secure, but at least we don't have to ship a private key around.

@eeeady - thoughts on that?

2021-05-26 18:30 UTC, eeeady commented on docs/runbooks/vpn-access-requests.md
> +    - `eclkc_centos_id_rsa` (may be sent separately and named differently)
Does it make more sense to push out everyone's public keys to the centos user across the fleet?

2021-05-26 18:37 UTC, rahearn commented on docs/runbooks/vpn-access-requests.md
> +    - `eclkc_centos_id_rsa` (may be sent separately and named differently)
Err, ideally each user would have their own actual user, rather than even everyone using `centos` with their own key. Again, it's a question about capturing small wins where we can while upgrading all the things

2021-05-28 18:22 UTC, kilbergr commented on docs/runbooks/vpn-access-requests.md
> +1. Enter your email and use the following for Common Name: `<<USERNAME>>.vpn.eclkc.info`
What's my username in this case? Same as AWS?

2021-05-28 19:07 UTC, eeeady requested changes
I tried this as is with Rebecca. I have a little feedback.

2021-05-28 19:07 UTC, eeeady commented on docs/runbooks/vpn-access-requests.md
> +1. Enter your email and use the following for Common Name: `<<USERNAME>>.vpn.eclkc.info`
I'd keep it same as AWS for consistency.

2021-05-28 19:07 UTC, eeeady commented on docs/runbooks/vpn-access-requests.md
> +1. Run `easyrsa import-req <<PATH_TO_CSR>> <<USERNAME>>`
These still don't work... should we replace with the commands that do work?

2021-05-28 19:07 UTC, eeeady commented on docs/runbooks/vpn-access-requests.md
> +1. Send `east.ovpn`, `/etc/openvpn/pki/ca.crt`, and `/etc/openvpn/pki/issued/<<USERNAME>>.crt` to the user
Is there a recommendation for how to send these files to the end user?

2021-05-28 19:42 UTC, kilbergr commented on docs/runbooks/vpn-access-requests.md
> +openssl pkcs12 -in <<FILE_NAME>>.p12 -nodes -out <<FILE_NAME>>.key -nocerts
```suggestion
openssl pkcs12 -in <<FILE_NAME>>.p12 -nodes -out <<USER_NAME>>.key -nocerts
```

2021-06-01 14:57 UTC, rahearn commented on docs/runbooks/vpn-access-requests.md
> +1. Send `east.ovpn`, `/etc/openvpn/pki/ca.crt`, and `/etc/openvpn/pki/issued/<<USERNAME>>.crt` to the user
No, these files are all public, so whatever works best is good.

2021-06-22 21:38 UTC, eeeady approved these changes
🚢 👍 lgtm!

2021-06-23 13:47 UTC, merged

2021-07-13 21:39 UTC, kilbergr commented on docs/runbooks/vpn-access-requests.md
> +    - `eclkc_centos_id_rsa` (may be sent separately and named differently)
Is this still an unresolved issue or can we resolve?