adding an onboarding checklist because it's time to set everyone up
OHS-Hosting-Infrastructure/infrastructure pull request #14
Opened 2021-05-20 14:03 UTC by eeeady

# [Create onboarding spreadsheet checklist for Hosting team ](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/9)

Changes proposed in this pull request:

- Adds checklist for onboarding a new hosting team member

2021-05-20 18:10 UTC, kilbergr requested changes
This is a great start. I'd love more detail so that folks who haven't done this before can follow a long.
Thank you!

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +__The new team member__ will need to complete the following:
Where do you complete these?

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Create ECLKC logins:
How do you do this? Can you link?

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Add the new member to email lists.
Can you enumerate email lists?

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] GitHub Org
```suggestion
- [ ] [GitHub Org](https://docs.github.com/en/organizations/managing-membership-in-your-organization/inviting-users-to-join-your-organization)
```

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] AWS (Read only)
Is there a how to for this and Qualys?

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] GitHub org
Right now I'm a member--looks like there is Owner and I believe Maintainer but not admin.

2021-05-20 18:10 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] SSH
What does Admin in SSH mean?

2021-05-20 19:47 UTC, rahearn commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Add the new member to existing calendar invites. This may mean reaching out to other
I think a word was out

2021-05-20 19:47 UTC, rahearn commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +TODO: Add set up documentation for each step.
I'd like to see this added sooner rather than later, since I forget how to do one or two of these steps.

2021-05-20 19:47 UTC, rahearn commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] VPN
Should we mention east/west here, or only add west to the `InfraSec` section below?

2021-05-20 20:17 UTC, eeeady commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Attempt and fail to log-in to jenkins.eclkc.info using the ECLKC Dev login. _Note: This gets your login into the Jenkins service so someone can add you to the right group._
Oh weird... As long as she can get in it's probably fine and I can remove.

2021-05-20 20:18 UTC, eeeady commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] GitHub org
I think I meant maintainer. I'll update in a bit.

2021-05-20 20:18 UTC, eeeady commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] AWS (Read only)
I'll add howtos in a bit.

2021-05-20 20:19 UTC, eeeady commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Create ECLKC logins:
Need to elaborate.

2021-05-20 20:20 UTC, eeeady commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +TODO: Add set up documentation for each step.
on it.

2021-05-20 21:32 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] SSH
How about: Grant SSH access to machines as root user
(how to would be great :) )

2021-05-20 21:47 UTC, kilbergr commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Create ECLKC logins:
Oh sorry, I meant: how do you create ECLKC logins for each of the environments? Is that info written down somewhere?

2021-06-01 14:40 UTC, jduss4 commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +  - [ ]  What is your favorite food?
I should have used this onboarding checklist, because I accidentally skipped this item :)

2021-06-01 14:57 UTC, jduss4 commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Create ECLKC logins:
I think that's explained in the documentation for `docs/runbooks/how-to-create-an-eclkc-login.md`

2021-06-04 19:37 UTC, kilbergr commented on docs/runbooks/how-to-create-an-eclkc-login.md
> +Go to [ECLKC Stage login](https://stage.eclkc.info/cas/login?service=https%3A%2F%2Fstage.eclkc.info%2F&locale=en`)
```suggestion
Go to [ECLKC Stage login](https://stage.eclkc.info/cas/login?service=https%3A%2F%2Fstage.eclkc.info%2F&locale=en)
```

2021-06-22 19:55 UTC, kilbergr reviewed
Much closer!

2021-06-22 19:55 UTC, kilbergr commented on docs/runbooks/how-to-get-ssh-access.md
> +1. Send a request for SSH access to the OHS Hosting team stating your team and vpn username.
```suggestion
1. Send a request for SSH access to the OHS Hosting team stating your team and VPN username (format: FirstinitialLastname).
```

2021-06-22 19:55 UTC, kilbergr commented on docs/runbooks/how-to-get-ssh-access.md
> +   * The OHS hosting team member will run the Ansible on the environment and then merge the PR.
I wouldn't know what "run the Ansible" entails in this circumstance. Do you have more detail?

2021-06-22 19:55 UTC, kilbergr commented on docs/runbooks/how-to-manage-qualys.md
> +4. This opens a popup where you'll enter in their name and email address. The other fields can be changed by the user later. Click "Save". The user should receive an email with a sign up link. Note t
```suggestion
4. This opens a popup where you'll enter in their name and email address. The other fields can be changed by the user later. Click "Save". The user should receive an email with a sign up link. Note the url in the email is only good for 24 hours.
5. Notify the user and ask them to go through the signup process and confirm with you they have access.
```

2021-06-22 21:44 UTC, eeeady commented on docs/runbooks/how-to-get-ssh-access.md
> +   * The OHS hosting team member will run the Ansible on the environment and then merge the PR.
attempted to make this more clear

2021-07-06 16:41 UTC, ssatagopan commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] Introduce yourself to the team on Slack:
Should we provide channel name?

2021-07-06 16:42 UTC, ssatagopan commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] [Add the new member to alias email lists](./how-to-manage-eclkcinfo-emails.md).
Should they create a ticket for these activities? Or existing team member creates it since new person wouldn't have access yet.

2021-07-27 23:44 UTC, eeeady commented on docs/runbooks/onboard-a-new-hosting-team-member.md
> +- [ ] [Add the new member to alias email lists](./how-to-manage-eclkcinfo-emails.md).
I think the existing team member creates it since the new person doesn't have access.

2021-08-03 19:41 UTC, ssatagopan approved these changes
LGTM

2021-08-03 22:35 UTC, merged