fill out research plan phase 1
OHS-Hosting-Infrastructure/infrastructure pull request #16
Opened 2021-05-28 15:54 UTC by kilbergr

# [Document and share interview questions for phase 1 of research #12](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/12)
and
# [Document phase 1 of research plan](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/11)

Changes proposed in this pull request:

- Add a Phase 1 of a research plan
- I'm pretty unsure of the timeline section, so....just leaving it there.

2021-05-28 17:28 UTC, eeeady requested changes
Looks good so far! I do think you've mixed up iLookout for iPD though?

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +  * iLookOut
iLookout is not actually an app under the national centers and is an application that's integrated with ipd.

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +* HSICC
HSICC is a team and not an application.

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +* National Centers
These are already in our infrastructure but may be sub applications of ECLKC.

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +We have the following goals for the initial round of research:
Great description of our goals!

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +We will be completing a Process download workshop with at least the HSICC team and likely the Coaching Companion and iLookOut teams. An example of that workshop is available [here](https://miro.com/a
When you write iLookOut, do you mean ipd?

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +We expect to work closely with members of the HSICC team, Coaching Companion, iLookOut team. The last we'll specifically be focusing on issues around the shared Central Authentication Service (CAS).
```suggestion
We expect to work closely with members of the HSICC team, Coaching Companion, iPD team. With the last team we'll specifically be focusing on issues around the shared Central Authentication Service (CAS). Alana Buroff, Information Systems and Communications Team lead, completed a stakeholder exercise and identified who we should speak to for the first round. She will be sending the introduction emails to stakeholder/users targeted in this user research plan. We will then follow up with the teams.
```

I think this is what you meant?

2021-05-28 17:28 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +We will be recording all these conversations via Zoom and sharing them with our partners at OHS and 18F.
** with consent?

2021-06-01 13:57 UTC, ssatagopan commented on docs/user-research/research-plan-phase1.md
> + * part of a product roadmap.
Should we adjust this to be "list of possible changes to prioritize in product roadmap" and then we go through prioritization exercise (bang for buck exercise) to construct actual roadmap?

2021-06-01 19:08 UTC, rahearn reviewed
I like this list of questions. I'd like @matt-dobson to also give this a review as a Researcher.

2021-06-02 15:41 UTC, jduss4 commented on docs/user-research/research-plan-phase1.md
> +  * Mobile Applications
Would you mind indenting the mobile apps (like the ECLKC Resource App, if you also manage that?, ELOF*, Ready-DLL, etc) ?  At a glance I didn't know that those were all mobile applications until I looked them up to read about them.

2021-06-02 18:20 UTC, kilbergr commented on docs/user-research/research-plan-phase1.md
> +We have already conducted the stakeholder mapping excercise (available [here](https://miro.com/app/board/o9J_lCdf5Iw=/?moveToWidget=3074457359393677819&cot=14)).
Thanks! Always looking for marginal gains!

2021-06-02 18:31 UTC, kilbergr commented on docs/user-research/research-plan-phase1.md
> +These are the goals for this project as defined by OHS:
Those I lifted from Alana during our Intro to OHS call. She had a document with them. These are my notes from that call: https://docs.google.com/document/d/13U7Swfn8BC0k9Z3KtFRlKVx43rbS6XnAfwx-rxSG7CU/edit

2021-06-02 18:42 UTC, kilbergr commented on docs/user-research/research-plan-phase1.md
> +Thank you for joining us today. My name is XXX and I’m an XXX [add your name and position] for Truss Works. We’re contracting with OHS to help manage and configure infrastructure for the apps under t
That's a good question. I'll add a mini def.

2021-06-02 18:43 UTC, kilbergr commented on docs/user-research/research-plan-phase1.md
> +### Architecture and Data
Oooh definitely. Smart to ask that last one before "Do you know when you have inconsistent data" especially.

2021-06-03 17:11 UTC, eeeady approved these changes
Just one typo fix. Thanks Rebecca!

2021-06-03 17:11 UTC, eeeady commented on docs/user-research/research-plan-phase1.md
> +  * iDP Learning Management System (includes iLookOut)
```suggestion
  * iPD Learning Management System (includes iLookOut)
```

2021-06-03 18:24 UTC, merged