adding info on how to restore db
OHS-Hosting-Infrastructure/infrastructure pull request #166
Opened 2021-08-03 16:33 UTC by eeeady

Follow up from yesterday's restore of coaching companion db.

Changes proposed in this pull request:

- Documentation of how to restore from backups

2021-08-03 16:45 UTC, kilbergr requested changes

2021-08-03 16:45 UTC, kilbergr commented on docs/runbooks/restore-db-mariadb.md
> +For example, to restore the `coaching_companion` database to the state it was as of this backup file:
Is this a different backup file than the one you are referencing? Or is this the one you created after running the duplicity command above? Aka where does this file come from?

2021-08-03 16:58 UTC, eeeady commented on docs/runbooks/restore-db-mariadb.md
> +For example, to restore the `coaching_companion` database to the state it was as of this backup file:
Created after running the duplicity command. it can be any sql file really.

2021-08-03 16:58 UTC, eeeady commented on docs/runbooks/restore-db-mariadb.md
> +The passphrase is stored in keepass under the entry `gpg mysql`.
do you not have access to keepass?

2021-08-03 22:34 UTC, kilbergr commented on docs/runbooks/restore-db-mariadb.md
> +For example, to restore the `coaching_companion` database to the state it was as of this backup file:
Not that I'm aware of.

2021-08-10 13:35 UTC, rahearn commented on docs/runbooks/restore-db-mariadb.md
> +The passphrase is stored in keepass under the entry `gpg mysql`.
I think a link to the box location for the vault (double checking that the link is limited to people who are actively shared to that file) and an instruction to get the key from a current member of the team would be a good addition to any place we reference the vault in these runbooks.

2021-08-10 13:35 UTC, rahearn commented on docs/runbooks/restore-db-mariadb.md
> +mysqldump <DATABASE NAME> > <BACKUP FILE NAME>.sql
The `<INSERT YOUR VALUE HERE>` format for these names is common, but I think a bad idea here because the stdin/out redirects get a bit lost. Maybe square brackets would work better?

2021-11-19 23:39 UTC, eeeady commented on docs/runbooks/restore-db-mariadb.md
> +mysqldump <DATABASE NAME> > <BACKUP FILE NAME>.sql
used square brackets

2021-11-19 23:47 UTC, eeeady commented on docs/runbooks/restore-db-mariadb.md
> +The passphrase is stored in keepass under the entry `gpg mysql`.
put this in ssm instead

2021-11-22 19:25 UTC, jduss4 approved these changes

2021-11-22 22:55 UTC, merged