Notification templates
OHS-Hosting-Infrastructure/infrastructure pull request #190
Opened 2021-08-17 14:03 UTC by ssatagopan

# [Notification Templates for Hosting System ](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/162)

A set of notification templates to be used when sending messages during incidents.

Changes proposed in this pull request:

- Initial version of templates

2021-08-17 23:10 UTC, kilbergr requested changes

2021-08-17 23:10 UTC, kilbergr commented on docs/how-we-work/notification-templates/acknowledgment-message.md
> +If an issue is P1 or P2 according to docs/how-we-work/support-process.md
```suggestion
If an issue is P1 or P2 according to [our support process doc definition](../support-process.md)
```

2021-08-17 23:10 UTC, kilbergr commented on docs/how-we-work/notification-templates/initial-message.md
> +If an issue is determined to be P0 or P1 based on docs/how-we-work/support-process.md
```suggestion
If an issue is determined to be P0 or P1 based on [our Support Process doc definition](support-process.md).
```

2021-08-17 23:10 UTC, kilbergr commented on docs/how-we-work/notification-templates/resolved-message.md
> +The following should be used as a message template when sending notifications about system outages and this is when the issue has been resolved.
Mention this is via email?

2021-08-17 23:10 UTC, kilbergr commented on docs/how-we-work/notification-templates/update-message.md
> +The following should be used as a message template when sending notifications about system outages and this is an update about an issue that is still happening.
Do you think it's worth mentioning this is via email?

2021-08-18 20:07 UTC, ssatagopan commented on docs/how-we-work/notification-templates/resolved-message.md
> +The following should be used as a message template when sending notifications about system outages and this is when the issue has been resolved.
Added

2021-08-18 20:07 UTC, ssatagopan commented on docs/how-we-work/notification-templates/update-message.md
> +The following should be used as a message template when sending notifications about system outages and this is an update about an issue that is still happening.
Added

2021-08-18 21:33 UTC, kilbergr approved these changes
LGMT TY

2021-08-23 13:41 UTC, merged