adding common actions for maintenance
OHS-Hosting-Infrastructure/infrastructure pull request #203
Opened 2021-08-23 22:03 UTC by eeeady

Changes proposed in this pull request:

- Adds a file that has some common commands that you might need during maintenance

2021-08-24 17:37 UTC, kilbergr requested changes
Most of these are to make it clearer for someone who knows less about how to do these things (me).

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Create a new volume from the AWS console.
```suggestion
1. Create a new volume from the AWS console Under Elastic Block Store > Volumes.
```

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Attatch the volume to the instance from the AWS console.
```suggestion
1. Attach the volume to the EC2 instance you are adding disk space to from the AWS console.
```

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. find the new device in /dev/
```suggestion
1. SSH onto the EC2 instance you attached the new volume to and find the new device in the `/dev/` directory.
```

Also--how does one id the new volume in `dev`? The things I think are volumes (e.g. `xvdb`) don't have anything that I recognize from what's available in the AWS console.

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +   1. Start the `fdisk` utility You should *not* have the disk you are editing with `fdisk` mounted.
```suggestion
   1. Start the `fdisk` utility. You should *not* have the disk you are editing with `fdisk` mounted.
```

I don't know what this means: "You should *not* have the disk you are editing with `fdisk` mounted."
Should I be writing `fdisk [options] <disk> ` to change the partition table?

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +   1. `n` to create a new partition.
These two options don't appear for me in fdisk

```
[centos@mariadb dev]$ fdisk
Usage:
 fdisk [options] <disk>    change partition table
 fdisk [options] -l <disk> list partition table(s)
 fdisk -s <partition>      give partition size(s) in blocks

Options:
 -b <size>             sector size (512, 1024, 2048 or 4096)
 -c[=<mode>]           compatible mode: 'dos' or 'nondos' (default)
 -h                    print this help text
 -u[=<unit>]           display units: 'cylinders' or 'sectors' (default)
 -v                    print program version
 -C <number>           specify the number of cylinders
 -H <number>           specify the number of heads
 -S <number>           specify the number of sectors per track
```

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Add a filesystem on top.
```suggestion
1. Add a `ext4` filesystem on top.
```

Is this a good guide on how to do: https://opensource.com/article/19/4/create-filesystem-linux-partition?

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Add a label to the new device to identify it.
Can you suggest a convention for the label?

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Add new device mount using the label to /etc/fstab so that it will automatically mounted on a reboot.
Is this a good guide of how to do: https://linuxhint.com/mount_partition_uuid_label_linux/ ?

2021-08-24 17:37 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +`apt-get install <package name>=<version>`
Did we decide to avoid adding repos/doing upgrades? Or is this worth adding?
https://ubiq.co/tech-blog/upgrade-apache-version-ubuntu/

2021-08-24 18:51 UTC, eeeady commented on docs/runbooks/maintenance.md
> +   1. `n` to create a new partition.
i thought that should drop you into the utility to manage the disk

2021-08-31 23:27 UTC, eeeady commented on docs/runbooks/maintenance.md
> +`apt-get install <package name>=<version>`
adding ppa's is not necessarly something I want us to go to. I'll add the link though.

2021-08-31 23:46 UTC, kilbergr reviewed
Some SMALL tweaks and then I think it should be ready.
I'm not approving it only bc I want to try it, but I am not blocking so it can be merged if Jerel tries and is happy.

2021-08-31 23:46 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +   1. `n` to create a new partition.
Thanks for this change. So I thought the device id would be something like `xvdd1` in MariaDB instance. However, when I run 
```
[centos@mariadb ~]$ fdisk /dev/xxdd1
fdisk: cannot open /dev/xxdd1: No such file or directory
```
What is the device id?

2021-08-31 23:46 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +   1. `n` to create a new partition.
Also, is "the disk you are editing with" the one that you're sshing into? I don't understand the differentiation you are making there.

2021-09-02 17:25 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Attach the volume to the EC2 instance you are adding disk space to from the AWS console.
```suggestion
1. Attach the volume to the EC2 instance you are adding disk space to from the AWS console. Note: The naming convention is different between AWS and what you'll see on disk. What we've found is that on disk, `xv` corresponds to `s`. So in the console you'll see, for example, `sdf` and on disk you'll see `xvdf1`.
```

2021-09-08 15:21 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +1. Add a `ext4` filesystem on top. Note, you may want an xfs file system but that will use different utlities.
Can you include why one chooses one file system over another? i.e. Why might you want an xfs? Is it just that you should check to see whatever the filesystem is for the disk you're enlarging?

2021-09-08 15:22 UTC, kilbergr approved these changes

2021-09-08 16:04 UTC, merged