updates all the incorrect tocs AND the maintenance instructions
OHS-Hosting-Infrastructure/infrastructure pull request #216
Opened 2021-09-15 14:26 UTC by kilbergr

# [[User Submitted] mariadb.east.eclkc/Disk Check - /var/backups is CRITICAL](https://ocio-jira.acf.hhs.gov/browse/OHSH-131)

Changes proposed in this pull request:

- Updates maintenance page with a lot more instructions for how to do various disk/volume changes
- Updates various TOCs in docs that were inaccurate.

**PLEASE HELP!**
There's a line (https://github.com/OHS-Hosting-Infrastructure/infrastructure/compare/rek-131-increase-disk-space?expand=1#diff-85e9d0513e5021b6c54bd48397c4a366d3498e677637372ab2014a41b78b737fR58) marked "XXXXXXXXX THIS PART. " where I am still a little confused what's happening. Can you check that what I've written is accurate and fully represents the action needed at that part? I'm still a little confused why we sync to the second disk (the temp one) and then mount to the first disk anyway (the preexisting one).

2021-09-21 00:45 UTC, eeeady requested changes
I think we are missing some info about making sure the new volume is bigger.

Additionally there was a line that looks like you wanted to replace? If not maybe take out the comment.

2021-09-21 00:45 UTC, eeeady commented on docs/runbooks/maintenance.md
> +## Create a new volume
Hah! I think something we both missed is when you create the new volume enter in a number greater than the size previously.

Also note you cannot downsize a volume from a snapshot.

2021-09-21 00:45 UTC, eeeady commented on docs/runbooks/maintenance.md
> +   1. Then [mount the replacement volume](#mount-a-disk) to the original disk. XXXXXXXXX THIS PART.
did you mean to delete or replace this line?

2021-09-21 16:44 UTC, kilbergr commented on docs/runbooks/maintenance.md
> +   1. Then [mount the replacement volume](#mount-a-disk) to the original disk. XXXXXXXXX THIS PART.
No--I wrote a note about it in the PR:

PLEASE HELP!
There's a line (https://github.com/OHS-Hosting-Infrastructure/infrastructure/compare/rek-131-increase-disk-space?expand=1#diff-85e9d0513e5021b6c54bd48397c4a366d3498e677637372ab2014a41b78b737fR58) marked "XXXXXXXXX THIS PART. " where I am still a little confused what's happening. Can you check that what I've written is accurate and fully represents the action needed at that part? I'm still a little confused why we sync to the second disk (the temp one) and then mount to the first disk anyway (the preexisting one).

2021-09-21 17:04 UTC, eeeady commented on docs/runbooks/maintenance.md
> +   1. Then [mount the replacement volume](#mount-a-disk) to the original disk. XXXXXXXXX THIS PART.
Got it! I'll take a look.

2021-09-22 21:14 UTC, eeeady commented on docs/runbooks/maintenance.md
> +   1. Then [mount the replacement volume](#mount-a-disk) to the original disk. XXXXXXXXX THIS PART.
OOH I SEE... lemme suggest a change.

2021-09-22 21:15 UTC, eeeady commented on docs/runbooks/maintenance.md
> +   1. Then [mount the replacement volume](#mount-a-disk) to the original disk. XXXXXXXXX THIS PART.
```suggestion
   1. Then [mount the replacement volume](#mount-a-disk) to the original mount path in the filesystem.
```

2021-09-27 16:54 UTC, jerels approved these changes
lgtm!!

2021-09-27 18:16 UTC, merged