adds cc cloud.gov doc
OHS-Hosting-Infrastructure/infrastructure pull request #252
Opened 2022-01-20 04:11 UTC by kilbergr

# [CC cloud.gov exploration](https://ocio-jira.acf.hhs.gov/browse/OHSH-277)

Changes proposed in this pull request:

- Adds docs describing the truials and tribulation of cloud.gov for cc with as few typos as possible!
I tried to represent folks' participation -- plzlmk if I left anytgihg out! @reid-truss @avanti-joshi

2022-01-20 15:25 UTC, ssatagopan requested changes
Besides the date, looks great. Thanks so much for getting this done!

2022-01-24 22:09 UTC, avanti-joshi requested changes

2022-01-24 22:09 UTC, avanti-joshi commented on docs/research/applications/cc-cloudgov.md
> +We wanted to determine how difficult it would be to get various applications on cloud.gov due to [the benefits it offers around compliance, security, and best practices](../design-docs/cloud-dot-gov-
```suggestion
We wanted to determine how difficult it would be to get various applications on cloud.gov due to [the benefits it offers around compliance, security, and best practices](../design-docs/cloud-dot-gov-feasibility). After the investigation of how difficult it would be to get the [ECLKC app on cloud.gov](../eclkc-cloudgov.md), we moved on to trying with Coaching Companion (CC). We believed CC would be the simplest to migrate to cloud.gov since it uses few services and only uses PHP on the backend. We were correct that it was much easier to get onto the platform than the ECLKC app. The biggest issues we encountered were with nginx configuration regarding routing. Although not fully fleshed out, we believe it would be a relatively low lift to transfer CC to cloud.gov.
```

2022-01-24 22:09 UTC, avanti-joshi commented on docs/research/applications/cc-cloudgov.md
> +Dayton clarified a few things for us. He said the vce-config copy we had was an example one that was out of date. Because it could contain sensitive info, they didn't include it in the repo. He also
I think we were a little confused about the nginx conf Dayton sent over and whether it was actually for CC since it differed from the prod configuration? not sure if we ever got confirmation on that

2022-01-24 22:09 UTC, avanti-joshi commented on docs/research/applications/cc-cloudgov.md
> +To load the database with what Dayton had sent us, I copied the sql dump to the Ansible/Nagios EC2 instance using scp (`scp -i myidentityfile -3 ~/Downloads/ccdump.sql centos@10.2.0.6:/home/centos/cc
might be worth noting that we had issues with `cf connect-to-service ` locally which is why we used the Ansible/Nagios machine, in case we ever run into that again

2022-01-24 22:09 UTC, avanti-joshi commented on docs/research/applications/cc-cloudgov.md
> +We could see errors in the php error log we had set up previously. It was telling us that certain extensions being used in the app were undefined. By adding them to a `PHP_EXTENSIONS` field in the `o
if it's easily accessible it could be helpful to list out the php extensions we added!

2022-01-25 22:16 UTC, kilbergr commented on docs/research/applications/cc-cloudgov.md
> +Dayton clarified a few things for us. He said the vce-config copy we had was an example one that was out of date. Because it could contain sensitive info, they didn't include it in the repo. He also
following up w dayton.

2022-01-26 20:40 UTC, rpdelaney commented
Since we have moved work tracking to JIRA, I have closed ass open issues with a script, including this one.

2022-01-26 20:40 UTC, rpdelaney commented
Oops.

2022-01-26 20:47 UTC, ssatagopan approved these changes

2022-01-26 22:12 UTC, avanti-joshi approved these changes

2022-01-27 17:27 UTC, merged