Add list of desired automation tasks
OHS-Hosting-Infrastructure/infrastructure pull request #253
Opened 2022-01-20 16:22 UTC by avanti-joshi

Changes proposed in this pull request:

- Add initial list of automated tasks brainstorms

2022-01-20 17:05 UTC, ssatagopan commented on docs/how-we-work/automated-actions.md
> +* Document our standard for where we configure Jenkins jobs
Jenkins job to update staging and dev ahead of production maintenance: [OHSH-355](https://ocio-jira.acf.hhs.gov/browse/OHSH-355)
Jenkins script to restart MariaDB: [OHSH-85](https://ocio-jira.acf.hhs.gov/browse/OHSH-85)

2022-01-20 17:07 UTC, ssatagopan requested changes
Added a couple of existing tickets, otherwise LGTM

2022-01-20 20:21 UTC, kilbergr reviewed
Lots of great IDEAS! Added some clarifying qs and a couplr of additions. Thank you !

2022-01-20 20:21 UTC, kilbergr commented on docs/how-we-work/automated-actions.md
> +
can we also evakuate and add/rm Jenkins access for team members as is reasonable (audit)?

2022-01-20 20:21 UTC, kilbergr commented on docs/how-we-work/automated-actions.md
> +* Trigger specified updates on specific hosts
Like pkg updates?

2022-01-20 20:21 UTC, kilbergr commented on docs/how-we-work/automated-actions.md
> +* Trigger specified updates on specific hosts
```suggestion
* Trigger specified updates on specific hosts
* Trigger specified package removal on specific hosts
```

2022-01-20 20:21 UTC, kilbergr commented on docs/how-we-work/automated-actions.md
> +* Investigate automating logging configuration on hosts
```suggestion
* Investigate automating logging configuration on hosts (including logrotate)
```

2022-01-20 20:21 UTC, kilbergr commented on docs/how-we-work/automated-actions.md
> +* Automatically run latest update on Stage and output report
Could we have a reach goal to automate creation of JIRA tickets when security vulns are found in scans (Qualys etc)?

2022-01-20 20:21 UTC, kilbergr commented on docs/how-we-work/automated-actions.md
> +
```suggestion
* [Create a jenkins job to restart MariaDB server](https://ocio-jira.acf.hhs.gov/browse/OHSH-85)
```

2022-01-20 23:08 UTC, kilbergr approved these changes
lgtm, thank you!

2022-01-21 17:12 UTC, ssatagopan approved these changes

2022-01-21 20:42 UTC, merged