OHSH-354 add initial writeup of plan to move jenkins behind vpn
OHS-Hosting-Infrastructure/infrastructure pull request #255
Opened 2022-02-01 20:44 UTC by avanti-joshi

# [Develop Plan to Move Jenkins Behind VPN](https://ocio-jira.acf.hhs.gov/browse/OHSH-354)

Changes proposed in this pull request:

- Add initial writeup of plan to move Jenkins behind VPN

2022-02-02 18:50 UTC, kilbergr requested changes
Hey, well done! I made a few comments but I think you've written two types of docs as one. You have an ADR on top (why we chose to do this), and the design doc underneath (how the set up will work). Would you mind splitting these into two documents and adding them to appropriate directories? Thank you.

2022-02-02 18:50 UTC, kilbergr commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +Currently Jenkins is available through the public internet. While there are controls to prevent unauthorized access, it's still not best practice to continue this since. We are also blocked on using
```suggestion
Currently Jenkins is available through the public internet. While there are controls to prevent unauthorized access, it's still not best practice to continue this since [XXX]. We are also blocked on using Jenkins for automation during deployments due to the current setup.
```
I think  you're missing a phrase here.

2022-02-02 18:50 UTC, kilbergr commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +Technical Story: [Develop Plan to Move Jenkins behind VPN](https://ocio-jira.acf.hhs.gov/browse/OHSH-354)
```suggestion
```
We don't typically include the tickets in design docs, tho I totally get the impulse.

2022-02-02 18:50 UTC, kilbergr commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +- Bad, Jenkins would still be in public subset
```suggestion
- Bad, Jenkins would still be in public subnet
```
Can you add why it's bad for Jenkins to be in a public subnet?

2022-02-02 18:50 UTC, kilbergr commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +- Good, Jenkins would be in private subnet
(restate the above of why Jenkins is better in privare subnet for our goals)

2022-02-02 18:50 UTC, kilbergr commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +- Bad, Jenkins redeploy required
Will you include the consequence here? i.e. why is it bad to redeploy Jenkins, especially at this time?

2022-02-03 21:50 UTC, rpdelaney commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Bad, This could result in some downtime for jenkins if there are any issues with the connection rules / implementing this change.
```suggestion
* Bad, This could result in some downtime for Jenkins if there are any issues with the connection rules / implementing this change.
```

2022-02-03 21:50 UTC, rpdelaney commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Bad, This could result in some downtime for jenkins if there are any issues with the connection rules / implementing this change.
This goes for anything we might do though, right?

2022-02-03 21:50 UTC, rpdelaney commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Bad, Jenkins redeploy required - this is a greater lift from the team, most of whom do not have access at the time. We also plan to stop using Jenkins as part of our future improvements to the syst
"Do nothing" is a good option to consider in an ADR: in this case, 'not doing work on something that we're going to blow up later anyway' could be a `+` for "Do nothing"

2022-02-07 17:20 UTC, kilbergr commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +Technical Story: [Develop Plan to Move Jenkins behind VPN](https://ocio-jira.acf.hhs.gov/browse/OHSH-354)
Bc it's relevant to the pr but I don't know the purpose for the doc itself. Are we ever working backwards from a doc to what the reqiested work was?

2022-02-07 17:29 UTC, kilbergr requested changes
JUST ONE MORE THING!!! Then YES~ thank you :)

2022-02-07 17:29 UTC, kilbergr commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Bad, Jenkins would still be in public subnet, which is not best practice given security considerations
Excellent start. Would you also include the security consideration so that that would be quickly understood by anyone reading this document? The point of this doc  is to elucidate every concern. Something like: "Since a public subnet is a subnet that's associated with a route table that has a route to an internet gateway, leaving Jenkins in the public subnet means it is theoretically accessible via the public internet. These concerns may be addressed using security groups." That's a little wordy and you can def simplify, but that's the thought you're looking to convey.

2022-02-07 17:29 UTC, kilbergr commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Good, Jenkins would be in private subnet, which is best practice given security considerations
Ditto above.

2022-02-07 17:40 UTC, reid-truss reviewed
mostly some clarifications/confirmations comments! thanks for putting this together.

2022-02-07 17:40 UTC, reid-truss commented on docs/adr/0011-jenkins-vpn-setup.md
> +We need to move the Jenkins machine behind the VPN so that the Jenkins login page can only be accessed when connected to the VPN.
probably worth specifying this is the UI for jenkins, and we already restrict ssh

2022-02-07 17:40 UTC, reid-truss commented on docs/adr/0011-jenkins-vpn-setup.md
> +## Decision Drivers
probably worth adding that we may retire jenkins in favor of another ci/cd system at some point in the future, so that's an influencing part of the decision too

2022-02-07 17:40 UTC, reid-truss commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Jenkins jobs can be created and used to automate deployments and many other currently manual processes
we could even specifically call out "improved security = improved confidence in granting jenkins additional permissions, which allows us to automate those tasks"

2022-02-07 17:40 UTC, reid-truss commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Bad, more risk of downtime in comparison to redeploying
hmm. an additional aspect of this is that it would be faster to roll back if there was a problem, vs. migrating to a new jenkins server entirely. so it's kind of different risk rather than more risk? I think either way there's a possible period of interruption for using jenkins

2022-02-07 17:40 UTC, reid-truss commented on docs/adr/0011-jenkins-vpn-setup.md
> +## Decision Drivers
I see now you mention that down below! might still be worth mentioning under decision drivers, but fine with me if you don't!

2022-02-07 17:40 UTC, reid-truss commented on docs/adr/0011-jenkins-vpn-setup.md
> +* Bad, would require communication to OHS teams
coordination, too, if we are batch moving/testing jobs

2022-02-07 17:40 UTC, reid-truss commented on docs/design-docs/moving-jenkins-behind-vpn.md
> + - Use an existing route53 entry and modify it to point to our Jenkins instance. Verify that this works as expected.
this would be the .east route53 A record and the private IP address, right? probably good to mention the private dns entry/ip address part here (I realize it's down below too)

2022-02-07 17:40 UTC, reid-truss commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +4) Inform teams of upcoming changes regarding accessing Jenkins. This will include:
I think someone mentioned this at some point in earlier discussions, but we should probably verify with the teams that use jenkins currently if they have any incoming webhooks into jenkins. restricting inbound to jenkins and that could cause some issues (as previously mentioned, outbound from jenkins will be fine so jenkins calling to github, for example, will keep working). I suspect they aren't, but we should definitely verify.

2022-02-07 17:40 UTC, reid-truss commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +   - Letting teams know that in the future they will have to be connected to the VPN to access Jenkins
We might need to grant vpn access to additional folks. Another thing we should confirm with the teams of who needs access to jenkins. We could probably also look at the current users (I think it's not many).

2022-02-07 17:43 UTC, rpdelaney commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +Technical Story: [Develop Plan to Move Jenkins behind VPN](https://ocio-jira.acf.hhs.gov/browse/OHSH-354)
I for one would be grateful for the link being there because it might lead me to an epic or other related info that's in the issue tracker and not git. If I don't need that then I won't click. It doesn't seem like a big cost to include it, especially since it's already there, but this is not a hill I will die on. :-)

2022-02-07 20:09 UTC, avanti-joshi commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +6) Add a security group rule to the existing Jenkins EC2 instance to only allow TCP / HTTP access from the VPN’s IP. This should block all traffic outside of the VPN to Jenkins.
Wouldn't we also need to add in a rule saying only allow HTTP access from the VPN's IP? along with removing the rule that currently allows external access?

2022-02-07 22:34 UTC, reid-truss commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +6) Add a security group rule to the existing Jenkins EC2 instance to only allow TCP / HTTP access from the VPN’s IP. This should block all traffic outside of the VPN to Jenkins.
Yeah, we'd need both. But one doesn't effect the other so its two independent changes. i.e. we will need to add the rule for internal http access to even test it, and then after we can remove the external http access

2022-02-07 22:36 UTC, avanti-joshi commented on docs/design-docs/moving-jenkins-behind-vpn.md
> +6) Add a security group rule to the existing Jenkins EC2 instance to only allow TCP / HTTP access from the VPN’s IP. This should block all traffic outside of the VPN to Jenkins.
got it! makes sense to me, thanks

2022-02-09 20:58 UTC, reid-truss approved these changes

2022-02-09 21:04 UTC, kilbergr approved these changes
LGTM thank you for  all this work!

2022-02-10 14:58 UTC, merged