Add ADR 0011 on cloud.gov
OHS-Hosting-Infrastructure/infrastructure pull request #256
Opened 2022-02-09 16:22 UTC by rpdelaney

# [OHSH-229](https://ocio-jira.acf.hhs.gov/browse/OHSH-229)

Changes proposed in this pull request:

- Add first draft of proposed ADR 0011: "On whether to migrate hosted OHS apps to cloud.gov or not"
- Ignore markdownlint "ul-style" rule since it was fighting with markdownlint-toc hook

I left `?`s where I feel there may be gaps others could fill in.

2022-02-10 15:45 UTC, ssatagopan requested changes

2022-02-10 15:45 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +
Some additional problems/context:
* Infrastructure and applications aren't built with horizontal scalability in mind (leading sometimes to responsiveness issues)
* App teams aren't able to confidently say that their applications will work in production environment because of differences in current infrastructure between dev/staging and prod

Found some earlier conversations on Slack also: https://trussworks.slack.com/archives/C01T6F5PB1A/p1631909491116900
https://trussworks.slack.com/archives/C01T6F5PB1A/p1632147056124200
https://trussworks.slack.com/archives/C01T6F5PB1A/p1633637098189500

2022-02-10 15:45 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- The project has a limited bugdet for infrastructure costs.
```suggestion
- The project has a limited budget for infrastructure costs.
```

2022-02-10 15:45 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- Wait until the hosted apps are ready for cloud.gov, then migrate everything
I know this is based on fairly recent conversations with Dan, but could we modify this bullet to say:
"Shore up existing infrastructure and help apps become 12F enough so they are ready for cloud.gov or any other platform"

2022-02-10 15:45 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +Wait until the hosted apps are ready for cloud.gov, then migrate everything, because
Would rephrase as per my previous comment that option is "Shoring up existing infrastructure and help apps become 12F enough..."

2022-02-10 15:45 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- We have a clear milestone to work toward that motivates needed modernization
Also lets us improve current infrastructure to make it more sustainable

2022-02-10 15:45 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +### Wait until the hosted apps are ready for cloud.gov, then migrate everything
Same comment as above about adjusting phrasing to reflect 12F enough...

2022-02-10 20:39 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- Good, because this is the shortest path to solving all the problems.
How about this?

```suggestion
- Good, because this is the shortest path to solving all the problems described in the context and problem statement.
```

2022-02-10 21:15 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +
> Infrastructure and applications aren't built with horizontal scalability in mind (leading sometimes to responsiveness issues)

Just checking - is this something that was specifically considered in the cloud.gov decision? ("Yes" is plenty good enough as an answer. just making sure I'm following)

> App teams aren't able to confidently say that their applications will work in production environment because of differences in current infrastructure between dev/staging and prod

Ah yes, Rebecca mentioned this also but I lost it in my disorganized notes. I added something about that point.

2022-02-10 21:20 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- Good, because this is the shortest path to solving all the problems.
3f0e75b

2022-02-10 21:35 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- Bad, because we have inadequate engineering bandwidth to put everything together
8a47ebc

2022-02-10 21:47 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- Bad, because cloud.gov requires containerization, and several hosted apps are currently
Does this get it? 3464dae

2022-02-10 21:47 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- We have a clear milestone to work toward that motivates needed modernization
What does 'sustainable' mean?

2022-02-10 22:32 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +
I'm concerned about constraining the scope of the ADR to what was actually considered a decision driver connected to the problem statement when the decision was being made. Can we chat about this offline?

2022-02-11 15:28 UTC, ssatagopan commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- We have a clear milestone to work toward that motivates needed modernization
> What does 'sustainable' mean?

Easier for hosting team to manage (less manual work, confidence in being resilient to user demand and resistant to malicious activity), more self-service for app teams

2022-02-14 17:38 UTC, rpdelaney commented on docs/adr/0011-on-migration-to-cloud.gov.md
> +- We have a clear milestone to work toward that motivates needed modernization
c9fd9c0

2022-02-14 19:38 UTC, reid-truss reviewed
I think a couple of Sanjay's comments might still be outstanding, but other than that, LGTM - thanks for researching and capturing this.

2022-02-14 20:01 UTC, ssatagopan commented on docs/adr/0012-on-migration-to-cloud.gov.md
This suggestion is for the opportunity cost of migrating one app vs. doing the shoring up work and getting to dev ops work

2022-02-14 20:13 UTC, ssatagopan approved these changes

2022-02-14 20:14 UTC, merged