Ansible usage adr
OHS-Hosting-Infrastructure/infrastructure pull request #261
Opened 2022-02-22 15:38 UTC by avanti-joshi

# [Write ADR for "Use ansible for configuration management"](https://ocio-jira.acf.hhs.gov/browse/OHSH-452)

Changes proposed in this pull request:

- Add ADR for using ansible for automating

2022-02-22 16:47 UTC, rpdelaney requested changes

2022-02-22 16:47 UTC, rpdelaney commented on docs/adr/0013-using-ansible-for-configuration.md
> +# Using Ansible For Host Configuration
The file should also be `git mv`'d to use the imperative form

2022-02-22 16:47 UTC, rpdelaney commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Good, because it's the easiest option
```suggestion
* Good, because it's the easiest option in the short term
```

2022-02-22 16:47 UTC, rpdelaney commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Bad, because many improvements to the system would be blocked by manual management of systems
```suggestion
* Bad, because many improvements to the system would be blocked by manual management of systems 
* Bad, because we can't reset state on the host if it is changed later
```
There is probably a better way to word this. I'm trying to get at how we can ssh into a box and change something, but then if that gets undone later, there's no playbook that will put it back how it should be. @reid-truss can you help?

2022-02-22 17:05 UTC, avanti-joshi commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Adhoc requests to add users to the VPN
Would adding more context to the manual process help? ex. how did we add users to machines pre automation, what's the process of adding users to the VPN

2022-02-22 17:58 UTC, rpdelaney commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Adhoc requests to add users to the VPN
IIRC I think the decision drivers weren't about what the technical process is exactly, so much that it's manual toil, prone to human error, and prone to configuration drift.

2022-02-22 20:32 UTC, avanti-joshi commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Adhoc requests to add users to the VPN
right that makes sense - I'll add a little bit context for both of these + the negative effects of the previous process

2022-02-22 21:47 UTC, rpdelaney commented on docs/adr/0013-use-ansible-for-configuration.md
> +* Adhoc requests to add users to machines and VPN - current manual process results in technical toil and lack of one source of truth that contains all user management information.Manually completing
```suggestion
* Adhoc requests to add users to machines and VPN - current manual process results in technical toil and lack of one source of truth that contains all user management information. Manually completing configuration tasks is more error prone in comparison to automating configuration tasks.
```

2022-02-22 21:54 UTC, avanti-joshi commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Bad, because many improvements to the system would be blocked by manual management of systems
what about something like "desired configuration state isn't tracked. If any changes are made, there's not way to check if the desired configuration was overridden. ex. if we wanted to test temporarily removing a user manually and forgot to add them back, there is no record of the fact that they should be on the system"

2022-02-23 15:58 UTC, reid-truss requested changes
Added a comment thread around some of the additional benefits of ansible we should capture, and how those illuminate some of the challenges of the other considered options as well. Let me know if you want to chat more about them!

2022-02-23 15:58 UTC, reid-truss commented on docs/adr/0013-use-ansible-for-configuration.md
> +Use Ansible to manage machine configuration. This decision was chosen because ansible was already configured and setup, making it an option that can be implemented quickly and fairly easily.
some additional benefits of Ansible given our situation:

Ansible is, generally, an agent-less idempotent configuration management tool - this means we:

- don't have to install an agent onto the hosts we manage with it (python and ssh are generally all that is needed)
- it (generally) will only run updates that need to be run (vs. scripting with bash, etc.)
- allows us to have some level of configuration as code, which means also leveraging code review processes when making changes via ansible, ensure it is repeatable, etc.
- doesn't require us to redeploy existing machines (vs. using a golden image/pre-packed AMI) to manage and make changes

2022-02-23 15:58 UTC, reid-truss commented on docs/adr/0013-use-ansible-for-configuration.md
> +Use Ansible to manage machine configuration. This decision was chosen because ansible was already configured and setup, making it an option that can be implemented quickly and fairly easily.
I think the above points can be extrapolated to fill in the pros/cons sections below for all the options as well. Just one example, a golden image/prepacked AMI would require redeploying systems to ensure that baseline amongst them, which we aren't well positioned for.

2022-02-23 16:56 UTC, rpdelaney commented on docs/adr/0013-using-ansible-for-configuration.md
> +* Bad, because many improvements to the system would be blocked by manual management of systems
> The desired configuration state isn't tracked against the actual: if any changes are made outside of Ansible, there's no way to check if the desired configuration was overridden. For example, if we wanted to test temporarily adding a user manually and forgot to remove them, there is no record of the fact that they should not be on the system.

If that works for you it works for me :)

2022-02-23 18:35 UTC, reid-truss approved these changes

2022-02-23 18:39 UTC, rpdelaney approved these changes

2022-02-23 20:39 UTC, merged