Ss atlassian adr
OHS-Hosting-Infrastructure/infrastructure pull request #263
Opened 2022-02-22 16:26 UTC by ssatagopan

# [OHSH-469](https://ocio-jira.acf.hhs.gov/browse/OHSH-469)

ADR for why we're going with Atlassian for OHS teams

Changes proposed in this pull request:

- ADR

2022-02-22 16:58 UTC, rpdelaney requested changes

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +# Atlassian suite for OHS IT teams
```suggestion
# Provide Atlassian suite for OHS IT teams
```

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +* Doesn't require engineering effort
```suggestion
* As a SaSS app, it doesn't require engineering effort to deploy
```

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +* Good, because several teams already use an Atlassian product so there should be less of a learning curve
```suggestion
* Good, because several teams already use an Atlassian products so there should be less of a learning curve
```

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +* Bad, because it makes us act as IT administrators
Is our existing process for support requests from app teams sufficient to handle this work?

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +Status quo of systems, but use process and communications to achieve objectives
What does this mean?

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +* Bad, because it doesn't address all the needs, specifically a consolidated view of teams for OHS
```suggestion
* Bad, because it doesn't address all the needs: specifically, a consolidated view of teams for OHS
```
nit

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +Chosen option: "Option 1", because it offers an integrated solution out of the box, can be configured and supported by non-engineers, allowing them to do more valuable engineering work, and can be us
```suggestion
Chosen option: "Option 1", because it offers an integrated solution out of the box, it can be configured and supported by non-engineers (allowing them to do more valuable engineering work), and can be used to support processes and communications while process only can only do so much.
```
nit

2022-02-22 16:58 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +As part of our project scope, we are tasked with helping facilitate collaboration and communication across OHS IT teams and moving OHS IT teams to more DevSecOps practices. We have made a start with
This section is rendering as a single paragraph. We need to add blank lines to get breaks.
```suggestion
The Office of Head Start (OHS) currently has several systems and applications being maintained and developed by different teams, both OHS and vendor teams. These include Early Childhood Learning & Knowledge Center (ECLKC), Head Start Coaching Companion (HS CC), Individualized Professional Development (iPD) Portfolio, Early Educator Central (EEC), TTA Hub, and several mobile apps. 

All these teams use different tools for their development processes, including task management, development, automated test, build and deploy, documentation, and support notifications. For example, the hosting team uses ACF Jira for task management, GitHub for code and documentation, and PagerDuty for support notifications, the HSICC team uses their own Jira for task management, GitHub for code, Jenkins for build and deploy, the Paradiso team uses Service Desk for task management, GitHub for code, etc.

These teams also follow different processes when it comes to their development and deployment pipeline. Some have a form of CI with automated tests while others do not. Some use Jenkins to deploy while others are updated by doing a git pull directly from the application server(s).
OHS has oversight responsibilities over all the systems that these teams build and maintain, yet there is no consolidated review system. There is also no consolidated or collaborative planning process when it comes to future work. The systems and teams are dependent on each other for some functionality yet they cannot always identify those dependencies ahead of time so that the teams can align their work together.

As part of our project scope, we are tasked with helping facilitate collaboration and communication across OHS IT teams and moving OHS IT teams to more DevSecOps practices. We have made a start with providing a Slack workspace and introducing a cross-team sprint review. However, teams still use separate tools and processes for development and deployment. And there is still not a coordinated planning activity across OHS so teams are still identifying dependencies too late.
```

2022-02-22 17:33 UTC, jerels approved these changes
LGTM, excited to see where this goes! 👍🏾

2022-02-23 14:38 UTC, ssatagopan commented on docs/adr/0013-atlassian-selection.md
> +Status quo of systems, but use process and communications to achieve objectives
Status quo of systems means the different teams still use whatever systems they use now, but we work with them to establish communication processes between the teams and also OHS as well so that coordination and oversight can happen, and also work with them to establish a CI pipeline with their existing systems.

2022-02-23 14:55 UTC, ssatagopan commented on docs/adr/0013-atlassian-selection.md
> +* Doesn't require engineering effort
Addressed in https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/263/commits/8a7369081af18e596d50eeaa866b1c14d62705d6

2022-02-23 16:48 UTC, rpdelaney commented on docs/adr/0013-atlassian-selection.md
> +* Bad, because it makes us act as IT administrators
OK, I don't think this blocks the ADR at all, just something that came to mind as I was reading

2022-02-24 00:52 UTC, rpdelaney approved these changes

2022-02-24 01:43 UTC, smvsmith approved these changes
Overall good! just a couple of phrases I thought could be refined. Thanks, Sanjay!

2022-02-24 01:43 UTC, smvsmith commented on docs/adr/0013-atlassian-selection.md
> +Chosen option: "Option 1", because it offers an integrated solution out of the box, can be configured and supported by non-engineers, allowing them to do more valuable engineering work, and can be us
Maybe we can rephrase to:

"....members--freeing up engineers to focus on delivering solutions--and..."

2022-02-24 01:43 UTC, smvsmith commented on docs/adr/0013-atlassian-selection.md
> +* Good, because it could still address the needs
sounds a little awkward to say "...the needs" and cut off, should it be something like "the needs of OHS as a whole"?

2022-02-24 14:41 UTC, ssatagopan commented on docs/adr/0013-atlassian-selection.md
> +Chosen option: "Option 1", because it offers an integrated solution out of the box, can be configured and supported by non-engineers, allowing them to do more valuable engineering work, and can be us
@smvsmith I left as is b/c solutions could be seen as vague in that even managing Atlassian is delivering a solution, while saying engineering work is the specific value add we're enabling.

2022-02-24 21:43 UTC, avanti-joshi approved these changes

2022-02-25 17:40 UTC, merged