compare vpn
OHS-Hosting-Infrastructure/infrastructure pull request #267
Opened 2022-03-04 00:51 UTC by mdrummerboy09

# [Research: Compare Community and Access Server Editions of OpenVPN and AWS's VPN Offering](https://ocio-jira.acf.hhs.gov/browse/OHSH-473)

2022-03-08 17:44 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +<!-- toc -->
```suggestion
<!-- mdformat-toc start --slug=github --no-anchors --maxlevel=6 --minlevel=1 -->
```
We recently switched from `markdownlint` to `mdformat`: this is the mdformat header for the table of contents.

2022-03-08 17:45 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +<!-- tocstop -->
```suggestion
<!-- mdformat-toc end -->
```

2022-03-08 17:46 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +This Is the free and open source version under the OpenVPN Items. All Configuring requires knowledge of Linux and ansible for deployments. Virtually Identical to the paid Access Server version but du
```suggestion
This is the free and open source version under the OpenVPN Items. All configuring requires knowledge of Linux and Ansible for deployments. Virtually identical to the paid Access Server version, but during a pairing session we discovered that there is no LDAP access. There is a compare sheet provided here (What Are The Main Differences Between OpenVPN Open Source And OpenVPN Access Server? | OpenVPN)
```
The hyperlink isn't working. It should be something like `[Text](url)`

2022-03-08 17:47 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +* Bad, Having to keep a deploy script up-to-Date
```suggestion
* Bad, because we must maintain deploy scripts
```

2022-03-08 17:51 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +* Bad, With a lack of documentation confusion can accrue
I'm not sure what this means re: the decision-making process that this ADR documents. Have we evaluated the docs for OpenVPN CE and found them lacking?

2022-03-08 18:48 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +* Date: 2022-23-2022
Date seems wrong

2022-03-14 19:26 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +* depending on the model type redeploying will require contacting OpenVPN to get a new access key
```suggestion
* Depending on the model type, redeploying will require contacting OpenVPN to get a new access key
```

2022-03-14 19:26 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +* Bad, there is no Support from OpenVPN directly, there are a few HOWTO guides to get started but most troubleshooting is through Wiki
```suggestion
* Bad, because there is no support from OpenVPN directly. There are a few HOWTO guides to get started, but most troubleshooting is through a wiki
```

2022-03-14 19:29 UTC, rpdelaney commented on docs/adr/0013-compare-vpn-edition.md
> +* bad, adding and managing new users
```suggestion
* Good, because everything stays within AWS
* Bad, because the hosting team is unfamiliar and would have to learn the new system
* Bad, because all users will need to be re-added and migrate to a new VPN client software
* Bad, because AWS VPN is not FIPS compliant, which could impact our ATO
```
I think this summarizes it? What do you think?

2022-03-15 16:36 UTC, ssatagopan requested changes
Have made suggestions for changes. Would add more information about the longer term drivers for decision vs. the initial setup and migration

2022-03-15 16:36 UTC, ssatagopan commented on docs/adr/0013-compare-vpn-edition.md
> +Additionally there is a BYOL (bring your own license) model. This will be the cheaper option of the two but making changes to the instance like imaging and relaunching it, or changing the instance ty
```suggestion
Additionally there is a BYOL (bring your own license) model. This will be the cheaper option of the two but making changes to the instance like imaging and relaunching it, or changing the instance type, or enabling auto-scaling, will result in the license key becoming invalid, requiring us to contact Support on this. The price for this will be $720 per year for the licenses and the cost of the EC2 instance
```

2022-03-15 16:36 UTC, ssatagopan commented on docs/adr/0013-compare-vpn-edition.md
> +From my initial research This VPN option seems confusing. It would take the hosting team some time to learn a new VPN system. All Users will need to be re-added and download a new VPN client software
```suggestion
From my initial research this VPN option seems confusing. It would take the hosting team some time to learn a new VPN system. All users will need to be re-added and download a new VPN client software. A factor that I have found is AWS VPN is not FIPS compliant and knowing this is government work that might have an impact on what we can do.
```

2022-03-15 16:36 UTC, ssatagopan commented on docs/adr/0013-compare-vpn-edition.md
> +
What about the actual functionality of the AWS VPN? Does it meet our needs and once we learn it, would it be easier to maintain and support than the other options?

2022-03-15 16:36 UTC, ssatagopan commented on docs/adr/0013-compare-vpn-edition.md
> +
What is the actual problem statement? "We need to decide on the VPN solution that meets our needs"?

2022-03-17 18:31 UTC, mdrummerboy09 commented on docs/adr/0013-compare-vpn-edition.md
> +
@ssatagopan I added so more information on AWS VPN. ultimately It could potentially be easier to maintain and support but II would have to test it first before I could give a definite answer

2022-03-17 19:59 UTC, ssatagopan requested changes
Looks good, but have one more question

2022-03-17 19:59 UTC, ssatagopan commented on docs/adr/0013-compare-vpn-edition.md
> +Chosen option: OpenVPN Access Server, Would be our best option going forward. the GUI will allow the hosting team manage users easily. Switching to Access Server will have the least amount of down ti
Can we go ahead and propose which Access Server option to go with in this ADR? BYOL or the other one?

2022-03-17 20:32 UTC, mdrummerboy09 commented on docs/adr/0013-compare-vpn-edition.md
> +Chosen option: OpenVPN Access Server, Would be our best option going forward. the GUI will allow the hosting team manage users easily. Switching to Access Server will have the least amount of down ti
Sounds good. I added the clarification on which OpenVPN I would recommend. which would be the one I link and not the BYOL

2022-03-18 13:45 UTC, ssatagopan approved these changes

2022-03-18 19:04 UTC, merged