ADR for private cert management - OHSH-511
OHS-Hosting-Infrastructure/infrastructure pull request #270
Opened 2022-03-11 15:47 UTC by jerels

# [Research Mail Server cert management options](https://ocio-jira.acf.hhs.gov/browse/OHSH-511)

Research around the options for going forward with managing private certificates.

2022-03-11 20:38 UTC, ssatagopan approved these changes
Would expand drivers to include other factors as well but otherwise, LGTM!

2022-03-11 20:38 UTC, ssatagopan commented on docs/adr/0015-private-cert-management.md
> +
I would match the drivers to the common factors in Good/Bad in the options. You mention cost, ease of use/automation/consistency

2022-03-11 20:41 UTC, rpdelaney requested changes

2022-03-11 20:41 UTC, rpdelaney commented on docs/adr/0015-private-cert-management.md
> +Using SSLMate for generating and managing private certificates seems to be the best option. It provides automation, alerts, and a web interface. SSLMate has also been previously vetted for use on the
```suggestion
Using SSLMate for generating and managing private certificates. It provides automation, alerts, and a web interface. SSLMate has also been previously vetted for use on the MilMove project.
```

2022-03-11 20:41 UTC, rpdelaney commented on docs/adr/0015-private-cert-management.md
> +- Good, because it seems to be the current way of operating. Which provides a certain kind of ease/consistency.
```suggestion
- Good, because it is the current way of operating. Which provides a certain kind of ease/consistency.
```

2022-03-11 20:41 UTC, rpdelaney commented on docs/adr/0015-private-cert-management.md
> +- Bad, because maintaining our own CA, or even multiple CAs, isn't advisable.
Can we say a little more about why not? Here, or in the decision drivers, or both?

2022-03-11 20:41 UTC, rpdelaney commented on docs/adr/0015-private-cert-management.md
> +- Good, because the cost scales by year. Rather by month.
```suggestion
- Good, because the cost scales by year, rather by month.
```

2022-03-11 20:55 UTC, kilbergr reviewed
Looking very good! I made a few small comments.

2022-03-11 20:55 UTC, kilbergr commented on docs/adr/0015-private-cert-management.md
> +- Good, because the cost scales by year. Rather by month.
Since you include cost of AWS private cert, would you mind including either the price or that it's a small enouhg amount that we can reasonably not worry about it?

2022-03-11 20:55 UTC, kilbergr commented on docs/adr/0015-private-cert-management.md
> +- Good, because it provides a central location for tracking and managing every private cert we would need.
Oh ! I didn't know! It's not through AWS or do we import it to AWS?

2022-03-11 20:55 UTC, kilbergr commented on docs/adr/0015-private-cert-management.md
> +- Bad, because starting at $400 a month for each private CA required to generate new private certs is fairly prohibitive.
All of these are applicable to this one too: 

```
- Good, because it provides alerting for certificate expiration.
- Good, because it provides alerting if something goes wrong during the renewal process
- Good, because it can automatically renew and install new certificates on to servers.
- Good, because it can automate the entire process of private cert generation.
```

2022-03-14 16:37 UTC, jerels commented on docs/adr/0015-private-cert-management.md
> +- Good, because it provides a central location for tracking and managing every private cert we would need.
yeah, SSLMate is it's own tool operating outside of our aws infrastructure. and as far as i'm aware we would be using either its cli or web console to manage the certs that we generate through them.

2022-03-14 21:38 UTC, kilbergr reviewed
I know you have some updates to make--holding off until we get those. You got this!

2022-03-15 20:46 UTC, ssatagopan approved these changes

2022-03-15 20:49 UTC, rpdelaney commented on docs/adr/0015-private-cert-management.md
> +Use AWS to generate and manage a single root CA, from which we can generate the needed private certificates. Seeing as our current setup of using non-qualified hostnames limits our options among thir
```suggestion
Use AWS to generate and manage a single root CA, from which we can generate the needed private certificates. Our use of non-qualified domain names limits third-party options, as they do not support this.
```

2022-03-15 20:49 UTC, rpdelaney commented on docs/adr/0015-private-cert-management.md
> +- Bad, because starting at $400 a month for each private CA required to generate new private certs is fairly prohibitive.
Is it prohibitive? That seems like a trivial amount of money.

2022-03-15 20:55 UTC, avanti-joshi approved these changes

2022-03-15 21:30 UTC, jerels commented on docs/adr/0015-private-cert-management.md
> +- Bad, because starting at $400 a month for each private CA required to generate new private certs is fairly prohibitive.
hmmm let me rework this one

2022-03-16 18:28 UTC, kilbergr approved these changes
Nicely done.

2022-03-16 19:41 UTC, rpdelaney approved these changes
It would be nice to rework the bit about $400 being "prohibitive" but it's not blocking. The ADR is greatly improved since I requested changes originally. Thank you!

2022-03-16 20:16 UTC, merged