How to retire an EC2 instance - OHSH-493
OHS-Hosting-Infrastructure/infrastructure pull request #271
Opened 2022-03-11 17:50 UTC by jerels

# [Plan retirement of ZTT-NAT-Dev](https://ocio-jira.acf.hhs.gov/browse/OHSH-493)

A how-to for retiring an EC2 instance. Some of this feels a little shaky as I'm not sure if I covered everything. I wrote out the steps that I took, but there's definitely missing bits. Like, no one had access to the actually server. So there might be steps to take if you do have that access. I also haven't actually retired an EC2 instance before, so the specifics around where to go in the console and the order to go in if there is associated terraform/resource are nonexistent. Any help or clarification in those areas would be helpful!!

2022-03-11 22:26 UTC, kilbergr requested changes
I left a bunch of comments but you captured most of the main concerns. Would you mind putting this as an ordered list? I also think this is a [Runbook](https://github.com/OHS-Hosting-Infrastructure/infrastructure/tree/main/docs/runbooks) rather than a How We Work. Thank you!

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +One day you will die. Your presence on this plane shall cease. And eventually all memory of you, fond or otherwise, will go with it. But do not despair, the same is true of all things. Including EC2
Do it for the lulz.

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +You might be here because the EC2 instance in question is being retired because you suspect it's no longer in use. Or you're spinning up a new one to correct the mistakes of the old one. Or even the
```suggestion
You are here because the EC2 instance in question is being retired. That might be because you suspect it's no longer in use, or you're spinning up a new one to correct the mistakes of the old one, or the hardware it lives on is being shutdown. **No matter the reason, reach out to any teams that you suspect would possibly be using the instance before doing anything else.** This'll inform how you should, or shouldn't, move forward, as well as give any affected parties the time to grieve.
```

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Use the IP address of the retiring instance to search the logs of any other instances that may interact with this one. To ensure it's not in active use.
Where are you searching the logs? In Cloudfront?
```suggestion
- Use the IP address of the retiring instance to search the logs of any other instances that may interact with this one to ensure it's not in active use.
```

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Once you have the go ahead, go about retiring the EC2 instance and the previously gathered associated resources and terraform.
```suggestion
- Once you have the go ahead, go about retiring the EC2 instance and the previously gathered associated resources either by running the terraform with the resources in question deleted or by manually removing them. You may have to delete things in a certain order due to dependencies.
```

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Track down and make a note of any resources that may be associated with and are **specific** to the retiring instance. i.e. security groups, volumes, etc.
```suggestion
- Make a note of any resources that may be associated with and are **not used** by the retiring instance. i.e. security groups, volumes, subnets, AMIs, snapshots, etc.
- If there are associated resources that are not specific to the retiring instance but have components that are, make note of those components (i.e. a security group used for a bunch of instances that has a rule specific to your retiring instance).
- Check that the instance is not a part of an autoscaling group. If it is and you delete it, it will just pop back up.
```

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
What should they do with the rest of the snapshots? Delete them? I think so but I'm not sure.

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Find and take note of any relevant bits of terraform. If any exist.
```suggestion
- Find and take note of any relevant bits of terraform if any exist.
```

2022-03-11 22:26 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Check the metrics of the instance on AWS console for any indications of life. It's best to compare to an instance that you're sure is still in use.
Can we get an explicit step in here about communicating with other teams/potential users?

2022-03-14 17:26 UTC, jerels commented on docs/how-we-work/retiring-an-instance.md
> +- Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
i'm thinking so as well, but do you feel more than one snapshot should be archived?

2022-03-14 17:49 UTC, jerels commented on docs/how-we-work/retiring-an-instance.md
> +- Check the metrics of the instance on AWS console for any indications of life. It's best to compare to an instance that you're sure is still in use.
i'm just not sure where to put that step. the warning above the steps is my attempt to reference that need. but i'm not sure at which point specifically, other than before beginning, one would reach out/initiate working with a particular team.

2022-03-14 21:39 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Check the metrics of the instance on AWS console for any indications of life. It's best to compare to an instance that you're sure is still in use.
Why not put it at the top of this list (after "breathe")?

2022-03-14 21:45 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
Maybe like 1 per month for the last year or something? I have 0 context on what the logical thing to do would be here. @ssatagopan do you know what the retention expectation is from OHS around AMIs (if they have one)? I didn't see anything in any of the repos about this issue.

2022-03-14 21:47 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Track down and make a note of any resources that may be associated with and are **specific** to the retiring instance. i.e. security groups, volumes, etc.
No, you're absolutely right. I am making the list slightly fuller (probably unnecessarily). While it's extremely unlikely a VPC would only have the EC2 instance, I think it may be more common for a subnet to be otherwise barren in a janky system. Since you're writing this for the general case, I included here. It's not necessary to include subnets as an example if you don't want to, but I do want the other change for readability. Make sense?

2022-03-15 15:42 UTC, avanti-joshi reviewed
Overall looks great and especially love the intro! had a few questions/clarifications

2022-03-15 15:42 UTC, avanti-joshi commented on docs/runbooks/retiring-an-instance.md
> +1. Find and take note of any relevant bits of terraform if any exist.
maybe we can specify that if terraform exists it would be in the environment configuration repo?

2022-03-15 15:42 UTC, avanti-joshi commented on docs/runbooks/retiring-an-instance.md
> +1. Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
is there any documentation on archiving snapshots that we could link to - or if it's a fairly intuitive process we don't have to, I'm just not familiar!

2022-03-15 16:53 UTC, ssatagopan commented on docs/how-we-work/retiring-an-instance.md
> +- Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
Our documentation around retention for backups is 1 year. I didn't see a requirement in the control that specifies it though, that 1 year is in our implementation statement:
"Backups are run Sunday through Saturday.  Each Amazon EC2 instance stores backups locally for 2 weeks and Amazon S3 holds backups for a year. Backup scheduling and status tracking is done through cron. The current drupal database backup scheme is to take a full backup every night and a binary log backup starting from the last full backup. "

2022-03-15 20:23 UTC, jerels commented on docs/how-we-work/retiring-an-instance.md
> +- Track down and make a note of any resources that may be associated with and are **specific** to the retiring instance. i.e. security groups, volumes, etc.
that makes sense, just made a small change to make that item more readable.

2022-03-15 20:28 UTC, jerels commented on docs/runbooks/retiring-an-instance.md
> +1. Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
gonna hold off on this part for now to get clarification on this step

2022-03-15 20:29 UTC, jerels commented on docs/runbooks/retiring-an-instance.md
> +1. Make a note of any resources that may be associated with and are **not used** by the retiring instance. i.e. security groups, volumes, subnets, AMIs, snapshots, etc.
made a change that should make this more readable. let me know what you think!

2022-03-15 20:57 UTC, avanti-joshi commented on docs/runbooks/retiring-an-instance.md
> +1. Make a note of any resources that may be associated with and are **not used** by the retiring instance. i.e. security groups, volumes, subnets, AMIs, snapshots, etc.
looks good to me, thanks!

2022-03-16 19:36 UTC, kilbergr commented on docs/how-we-work/retiring-an-instance.md
> +- Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the most recent snapshot. You'll cherish those memories later.
OK so here's some info about how archiving works and what it does:
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/snapshot-archive.html
It sounds like we should be archiving the last year of snapshots and deleting anything earlier than that. They will continue to get deleted as time moves forward if cron is functioning as described. Perhaps we need an additional check to retain the latest backup after 1 year (I'm not sure if we do that). I don't see the benefit to retaining them as standard snapshots rather than as archived snapshots.

2022-03-16 21:13 UTC, kilbergr commented on docs/runbooks/retiring-an-instance.md
> +1. Check to see if there are any snapshots being taken of the attached volume. If so be sure to archive the last year's worth of snapshots, deleting anything older than that. You'll cherish those mem
```suggestion
1. Check to see if there are any snapshots being taken of the attached volume. If so, archive the last year's worth of snapshots. Cron should be deleting anything older than that. You'll cherish those memories later.
```

2022-03-17 13:21 UTC, avanti-joshi approved these changes

2022-03-17 17:12 UTC, kilbergr approved these changes
TY! Great job sticking to it and getting this over the line. I know there was a lot of back and forth.

2022-03-17 20:27 UTC, merged