[OHSH-520](https://ocio-jira.acf.hhs.gov/browse/OHSH-520) add initial private ca documentation
OHS-Hosting-Infrastructure/infrastructure pull request #275
Opened 2022-04-06 20:12 UTC by avanti-joshi

# [Document how to use the Private Certificate Authority in AWS](https://ocio-jira.acf.hhs.gov/browse/OHSH-520)

Changes proposed in this pull request:

- Adding documentation around how to use Private CA to create certificates

2022-04-06 21:09 UTC, rpdelaney approved these changes
Approved with comments - please make changes and merge.

This is a great start. Good job!

2022-04-06 21:09 UTC, rpdelaney commented on docs/how-we-work/private-ca.md
> +More information about importing a private CA via terraform can be found [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/acmpca_certificate_authority)
```suggestion
More information about importing a private CA via terraform can be found [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/acmpca_certificate_authority).
```

2022-04-06 21:09 UTC, rpdelaney commented on docs/how-we-work/private-ca.md
> +For Windows:
Do we have a use case for doing this on Windows? If not, omitting the `certutil` stuff may make the document a faster read.

2022-04-06 21:09 UTC, rpdelaney commented on docs/how-we-work/private-ca.md
> +The OHS private CA was created using the [acmpca certificate authority](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority) terraform module. Not
```suggestion
The OHS private CA was created using the [ACM Private Certificate Authority](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaWelcome.html) Terraform [module](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority). Note that as stated in the Terraform module, a the manual step of installing the root CA certificate from the console is required to change the status of the CA from pending to active. This is a one time action that only has to be done when creating a new Private CA.
```

2022-04-07 18:43 UTC, avanti-joshi commented on docs/how-we-work/private-ca.md
> +For Windows:
@rpdelaney the reason I included it was incase we needed it when sending instructions to the app teams / jenkins users. Wasn't sure if all of OHS has Macs

2022-04-07 18:44 UTC, avanti-joshi commented on docs/how-we-work/private-ca.md
> +For Windows:
if we have confirmation on that though I definitely agree it doesn't need to be included

2022-04-07 18:54 UTC, rpdelaney commented on docs/how-we-work/private-ca.md
> +For Windows:
Ahh yeah good thinking. Works for me.

2022-04-08 16:00 UTC, kilbergr requested changes
Looking very good but I do have a few minor questions.

2022-04-08 16:00 UTC, kilbergr commented on docs/how-we-work/private-ca.md
> +The OHS private CA was created using the [ACM Private Certificate Authority](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaWelcome.html) Terraform [module](https://registry.terraform.io/pro
```suggestion
The OHS private CA was created using the [ACM Private Certificate Authority](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaWelcome.html) Terraform [module](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority). Note that as stated in the Terraform module, the manual step of installing the root CA certificate from the console is required to change the status of the CA from pending to active. This is a one time action that only has to be done when creating a new Private CA.
```

2022-04-08 16:00 UTC, kilbergr commented on docs/how-we-work/private-ca.md
> +Terraform supports importing a aws_acmpca_certificate_authority resource as a datatype by it's arn. An example of this is below:
```suggestion
Terraform supports importing a aws_acmpca_certificate_authority resource as a datatype by its arn. An example of this is below:
```

2022-04-08 16:00 UTC, kilbergr commented on docs/how-we-work/private-ca.md
> +Terraform supports importing a aws_acmpca_certificate_authority resource as a datatype by it's arn. An example of this is below:
Do we want to be importing them as a data type? I would imagine if we're pulling in to manage with tf, we'd want to import as the resource. Am I misunderstanding the use case?

2022-04-08 16:00 UTC, kilbergr commented on docs/how-we-work/private-ca.md
> +Without any modifications to your local machine "trust" settings, navigating to a website that uses a certificate signed by the OHS Private CA will result in certificate errors. To resolve these, you
Can you recommend a location to save the cert?

2022-04-08 19:27 UTC, kilbergr approved these changes
TY for changes!

2022-04-08 19:35 UTC, merged