OHSH-536 Adding new documentation for Qualys scan triage
OHS-Hosting-Infrastructure/infrastructure pull request #276
Opened 2022-04-19 23:40 UTC by reid-truss

# [OHSH-536 Review Qualys scans](https://ocio-jira.acf.hhs.gov/browse/OHSH-536)

This PR adds more documentation around managing scan results from Qualys, including how to more easily manage results and generate Jira tickets.

Changes proposed in this pull request:

- improved documentation for Qualys scans management

2022-04-20 17:50 UTC, rpdelaney requested changes

2022-04-20 17:50 UTC, rpdelaney commented on docs/runbooks/how-to-manage-qualys.md
> +  1. Update the priority on the ticket to match the _Severity_ of the finding in Qualys - for example, severity of 5 would be the highest priority
Does the number of possible severities correspond to the range of priorities in Jira so that this maps 1:1? Or is the idea that the reviewer should make a judgment call about what the priority of the Jira issue should be? The latter makes sense to me, especially since priorities can always change later and the main thing is just to get the tickets in the backlog. But maybe giving explicit permission for that here would help.

2022-04-20 17:50 UTC, rpdelaney commented on docs/runbooks/how-to-manage-qualys.md
> +      1. Example: a cluster of Kernel Advisories for a specific system where the old kernels need to simply be cleaned from the system. In cases like this, consider prefixing the ticket with CVE-* .
```suggestion
      1. Example: a cluster of Kernel Advisories for a specific system where the old kernels need to simply be cleaned from the system. In cases like this, consider prefixing the ticket with "CVE-*". Example: "CVE-* Kernel Security Advisories for ZTT-NAT"
```

2022-04-20 17:50 UTC, rpdelaney commented on docs/runbooks/how-to-manage-qualys.md
> +    1. EOL - Ex. EOL Migrate Server X from Ubuntu16 to Ubuntu18
```suggestion
    1. EOL - Example: "EOL Migrate Server X from Ubuntu16 to Ubuntu18"
```

2022-04-21 14:24 UTC, reid-truss commented on docs/runbooks/how-to-manage-qualys.md
> +  1. Update the priority on the ticket to match the _Severity_ of the finding in Qualys - for example, severity of 5 would be the highest priority
It maps to the priority levels available, and there are legal requirements for response based on severity, if I'm not mistaken, so I want to make sure the actual severity in Qualys is captured and communicated in this instance. The actual priority of the ticket being worked on will still be something that we (and Sanjay/Serafina) more actively manage.

2022-04-21 19:39 UTC, rpdelaney approved these changes
How does that look?

2022-04-21 19:54 UTC, rpdelaney commented
> [Reid Lewis (they/them)](https://app.slack.com/team/U02MHRR3LHG)  [3 minutes ago](https://acf-ohs.slack.com/archives/C02ML80QH8U/p1650570609565699?thread_ts=1650562790.264999&cid=C02ML80QH8U)
any way we can make 4, 5, 6 bullets into sub bullets?
> [Reid Lewis (they/them)](https://app.slack.com/team/U02MHRR3LHG)  [3 minutes ago](https://acf-ohs.slack.com/archives/C02ML80QH8U/p1650570612210849?thread_ts=1650562790.264999&cid=C02ML80QH8U)
otherwise lgtm

2022-04-25 18:20 UTC, reid-truss commented
@rpdelaney I just tweaked the bullet points a little bit more, and I'm happy with it if you're good with it.

2022-04-25 20:47 UTC, rpdelaney commented
Ship it!

2022-04-25 21:04 UTC, merged