Adding understanding current VPN Iimplementation
OHS-Hosting-Infrastructure/infrastructure pull request #278
Opened 2022-04-25 20:28 UTC by mdrummerboy09

# [OHS-449: Research: Understand current VPN implementation](https://ocio-jira.acf.hhs.gov/browse/OHSH-449)

Changes proposed in this pull request:

- Adding research into how the VPN is currently being used

2022-04-26 00:08 UTC, kilbergr requested changes
Hi Mondo--
There are a lot of comments here but they're all about working the language to get greater clarity for those of us less familiar with the information than you. You've done the heavy lifting of getting the content, now it's just a matter of making sure others can  understand it as well as you do. Please tag me again when you need another review. Thank you SO MUCH for tackling. This is hard work!

2022-04-26 00:08 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +OpenVPN is located in the Shared-VPC and can communicate to dev and prod because of __server.conf__ it is allowing those IPs trough.
```suggestion
OpenVPN is located in the Shared VPC and can communicate to dev and prod because of __server.conf__ it is allowing those IPs through.
```

Some things I'm guessing based on this:
I know OpenVPN is a VPN system. Are you referring to the VPN server here?
dev and prod are Dev and Prod VPCs.

If that's correct, here's how I'd phrase:
OpenVPN is on the `VPN` server, which is in the Shared VPC. The VPN can communicate to servers on Dev and Prod VPCs because of the `server.conf` set up described in the [Routing & ports](#Routing-&-ports) section of this doc.

2022-04-26 00:08 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +shared VPC is peered with the other VPCs. This allows communication and that security groups are leveraged at individual EC2 level.
```suggestion
The shared VPC is peered with the other VPCs. This allows communication and that security groups are leveraged at individual EC2 level.
```

I don't understand what you mean by this statement: This allows communication and that security groups are leveraged at individual EC2 level.
Can you try again?

2022-04-26 00:08 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +As with the OpenVPN Server Port 1194 UDP needs to be open and allowed traffic.
```suggestion
As with the OpenVPN Server, Port 1194 (UDP) needs to be open and allow traffic.
```

2022-04-26 00:08 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +The main SG attached to the VPN and all SGs must have an inbound rule to allow SSH from VPN.
```suggestion
All SGs, including the main SG attached to the VPN, must have an inbound rule to allow SSH from VPN.
```

2022-04-26 21:15 UTC, mdrummerboy09 commented on docs/research/vpn-implentation.md
> +After going over the configuration, the __server.conf__ is nearly Identical to the __sample-server.conf__ that is provided by OpenVPN CE. That being said there are some key difference.
I will add that the only difference is what subnets are open and where the CA are stored.

2022-04-26 21:48 UTC, mdrummerboy09 commented on docs/research/vpn-implentation.md
> +shared VPC is peered with the other VPCs. This allows communication and that security groups are leveraged at individual EC2 level.
I'll be honest I didn't know what I mean by that statement its like my brain just spliced two thoughts together. 

this is what I was trying to say:

The shared VPC is peered with the Dev and Prod VPCs. This allows VPN server to communicate to the other services and leverages security groups and the individual EC2 level.

2022-04-26 22:11 UTC, mdrummerboy09 commented
@kilbergr thanks for all the comments. this really helps me in the area I struggle with. I appreciate it a lot!

2022-04-26 23:44 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +shared VPC is peered with the other VPCs. This allows communication and that security groups are leveraged at individual EC2 level.
Awesome. I understand that!

2022-04-27 00:03 UTC, kilbergr requested changes
Looking much better! A few things left to clean up and then I think you're good.

2022-04-27 00:03 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +crypto was generated using Diffie Hellman Command
I still don't know what is salient about this piece of information, nor do I know what "crypto" refers to--is it the cryptographic key currently in use? Why is it important that we know how these were generated? Is it because we may have to generate in the future?

2022-04-27 00:03 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +OpenVPN is located in the Shared VPC and can communicate to dev and prod because of __server.conf__ it is allowing those IPs through.
```suggestion
```

2022-04-27 00:03 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +OpenVPN is located in the Shared VPC and can communicate to dev and prod because of __server.conf__ it is allowing those IPs through.
This statement has become redundant.

2022-04-27 00:03 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +The shared VPC is peered with the Dev and Prod VPCs. This allows VPN server to communicate to the other services and leverages security groups and the individual EC2 level.
```suggestion
The shared VPC is peered with the Dev and Prod VPCs. This allows VPN server to communicate to the other services and leverages security groups at the individual EC2 level.
```

2022-04-27 22:27 UTC, mdrummerboy09 commented on docs/research/vpn-implentation.md
> +This creates a Piblic Key Infrastructure (PKI) allowing clients to connect to the server to access OpenVPN.
ok so my understanding of Easy-RSA is it creates the PKI and Diffie Hellman helps encrypt and decrypt  those keys created.

2022-04-27 22:29 UTC, mdrummerboy09 commented on docs/research/vpn-implentation.md
> +crypto was generated using Diffie Hellman Command
I was having a hard time trying to understand and explain this to myself but my understanding is that DH encrypts and decrypts the private and public keys. thus creating another layer of security and is recommended by OpenVN

2022-04-28 19:14 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +OpenVPN uses the Diffie Hellman process to encrypt and decrypt the keys generated by \[easy-rsa\](https://github.com/OpenVPN/easy-rsa, creating another level of security that OpenVPN recommends.
```suggestion
OpenVPN uses the Diffie Hellman process to encrypt and decrypt the keys generated by [easy-rsa](https://github.com/OpenVPN/easy-rsa), creating another level of security that OpenVPN recommends.
```

2022-04-28 19:14 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +crypto was generated using Diffie Hellman Command
Great. Thank you.

2022-04-28 19:15 UTC, kilbergr approved these changes
Great work. Thanks for sticking to it. I have 2 minor edits (one a typo, one a markdown issue) and then I say you're good to go.

2022-04-28 19:15 UTC, kilbergr commented on docs/research/vpn-implentation.md
> +the command to accomplish that is below.
```suggestion
The command to accomplish that is below.
```

2022-04-28 21:16 UTC, reid-truss reviewed
just a couple of typos and clarifications! otherwise this is looking great

2022-04-28 21:16 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +The server itself sets in the subnet of __10.8.0.0/24__ and all the clients virtual Ip address are stored in an _ipp.txt_ file. This is in case if the Server is restarted or fails.
typo - sets should be sits

2022-04-28 21:16 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +The server itself sets in the subnet of __10.8.0.0/24__ and all the clients virtual Ip address are stored in an _ipp.txt_ file. This is in case if the Server is restarted or fails.
can remove "if" from the last sentence here

2022-04-28 21:16 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +Port 1194 UDP, Is the the main and default listening port for OpenVPN.
remove the comma after UDP

2022-04-28 21:16 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +Root Cert (CA) are made by using [easy-rsa](https://github.com/OpenVPN/easy-rsa) repo and are kept `/etc/openvpn,easy-rsa/keys`.
is that path for the easy-rsa keys right? wonder if the comma in it should be a /

2022-04-28 21:16 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +The hosting team should be able to copy all the keys and certs over to a new server with little effort, although some testing may be needed before deployment.
is this true for switching to Access Server from community server? should specify if it's just community edition

2022-04-28 21:16 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +Following the request, Requesters would need SSH Access and those steps can be found here: [how to get SSH Access](https://github.com/OHS-Hosting-Infrastructure/infrastructure/blob/main/docs/runbooks
should specify the ssh access is for whatever servers they are requesting, this reads as ssh to the vpn server which we don't want

2022-04-28 21:19 UTC, reid-truss commented on docs/research/vpn-implentation.md
> +The hosting team should be able to copy all the keys and certs over to a new server with little effort, although some testing may be needed before deployment.
clarified with Mondo on zoom that this works for both AS and CE

2022-04-28 21:25 UTC, reid-truss approved these changes

2022-04-28 21:31 UTC, merged