Task Management ADR
OHS-Hosting-Infrastructure/infrastructure pull request #53
Opened 2021-06-11 15:42 UTC by ssatagopan

# Evaluate and select task management system(https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/31)

Changes proposed in this pull request:

- Initial version of ADR with proposed selection for task management SW

2021-06-12 00:21 UTC, kilbergr reviewed
So I think this is a reasonable outcome, but I do wonder why the Truss default, Pivotal Tracker, wasn't on this list. Is there anything that makes it an obvious no go? I am fine with JIRA--just wanted to check in.
I would definitely find out what the price estimate is.

2021-06-14 13:32 UTC, ssatagopan commented
> So I think this is a reasonable outcome, but I do wonder why the Truss default, Pivotal Tracker, wasn't on this list. Is there anything that makes it an obvious no go? I am fine with JIRA--just wanted to check in.
> I would definitely find out what the price estimate is.

That's a very good point. I didn't include it only b/c I didn't think of it.

2021-06-14 13:54 UTC, ssatagopan commented
Added PivotalTracker to ADR. Still proposing JIRA, mainly due to more flexibility to accommodate different workflows as well as ticket attributes and timeline/planning functions

2021-06-14 15:58 UTC, rahearn approved these changes
LGTM - there is one extra bullet on the list of options that could be cleaned up, but it's also not hurting anything

2021-06-21 20:20 UTC, eeeady approved these changes
Generally I'm happy with this. I do think before we execute we need to figure out the costs for using JIRA and the overhead for getting it ATO'ed.  I _highly_ suggest noting that JIRA we are hoping for will be JIRA Cloud. If we have to self host, there will be be year over year maintenance overhead that makes JIRA less appealing.

2021-06-22 18:13 UTC, kilbergr requested changes
I agree with Eady--if we have to self host JIRA, I would push for Pivotal instead because nobody (on this team) has time for that. I would also find out what the costs are. If cost is prohibitive, that will cancel it out as an option.

2021-06-22 18:13 UTC, kilbergr commented on docs/adr/004-task-management-sw.md
> +* … <!-- numbers of pros and cons can vary -->
I would also add that it's a complex product that requires lots of configuration in my experience.

2021-06-22 18:13 UTC, kilbergr commented on docs/adr/004-task-management-sw.md
> +* Bad, because it does not seem to have built-in time line or planning functions
It has burn down charts I believe. Is this not what you're describing?

2021-06-22 19:58 UTC, ssatagopan commented on docs/adr/004-task-management-sw.md
> +* Bad, because it does not seem to have built-in time line or planning functions
> It has burn down charts I believe. Is this not what you're describing?

No, I'm talking about being able to track expected completion dates/actual completion dates and roadmapping tools

2021-06-22 20:01 UTC, ssatagopan commented on docs/adr/004-task-management-sw.md
> +* … <!-- numbers of pros and cons can vary -->
> I would also add that it's a complex product that requires lots of configuration in my experience.

Added

2021-06-22 20:04 UTC, ssatagopan commented
> So I think this is a reasonable outcome, but I do wonder why the Truss default, Pivotal Tracker, wasn't on this list. Is there anything that makes it an obvious no go? I am fine with JIRA--just wanted to check in.
> I would definitely find out what the price estimate is.

Added note that we are evaluating JIRA Cloud

2021-06-22 20:08 UTC, kilbergr commented on docs/adr/004-task-management-sw.md
> +* Bad, because it does not seem to have built-in time line or planning functions
Gotcha!

2021-06-22 20:09 UTC, kilbergr commented
So--do you think we need the cost to make a choice? Or no?
LMK what you think and I'll approve if you think it's unnecessay.

2021-06-22 20:18 UTC, ssatagopan commented
> So--do you think we need the cost to make a choice? Or no?
> LMK what you think and I'll approve if you think it's unnecessary.

I think we do need cost to make a choice, so I would leave it unmerged until we decide. Still waiting on ACF JIRA owner to communicate that. I should have cost for ServiceNow in a couple days so we could compare with that at least. I've reached out to Pivotal as well for a quote.

2021-06-23 12:35 UTC, ssatagopan commented
@kilbergr Based on our discussion during sprint planning, if you're ok with my updates, let me know and I'll go ahead and merge PR but keep issue open

2021-06-24 16:54 UTC, kilbergr approved these changes
Works for me !

2021-06-24 18:01 UTC, merged