How We Work updates
OHS-Hosting-Infrastructure/infrastructure pull request #76
Opened 2021-06-24 15:26 UTC by ssatagopan

# [Sprint Planning update](https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-63184494)

Changes proposed in this pull request:

- Added Conventions section
- Updated Sprint Planning section

2021-06-24 18:26 UTC, kilbergr requested changes
So I think your additions are ab fab. However, if this is for the ticket about updating our sprint process, I think there's more to be added. One thing that stands out to me is there's no mention of grooming. Another is that we are doing 1 week sprints.

2021-06-24 18:26 UTC, kilbergr commented on docs/how-we-work/README.md
> + * Epics or high level initiative name is put in square brackets at beginning of ticket title
```suggestion
  * All team members vote on points, whether or not they're in a technical role. 
  * Epics or high level initiative name is put in square brackets at beginning of ticket title
```

2021-06-24 18:26 UTC, kilbergr commented on docs/how-we-work/README.md
> +   * 1: Well-understood and can be completed without requiring interaction between teams within 1 day
```suggestion
   * 1: Well-understood and can be completed without requiring interaction between teams in less 1-2 work hours
```

2021-06-24 18:26 UTC, kilbergr commented on docs/how-we-work/README.md
> +   * 2: Well-understood and can be completed with little to no interaction between teams in a few days
```suggestion
   * 2: Well-understood and can be completed with little to no interaction between teams within half a day of concentrated work
```

2021-06-24 18:26 UTC, kilbergr commented on docs/how-we-work/README.md
> +   * 3: Some ambiguity or well understood but requires interaction with other teams that may delay completion
```suggestion
   * 3: Some ambiguity or well understood but requires interaction with other teams that may delay completion, likely would take 1 full work day
```

2021-06-24 20:25 UTC, ssatagopan commented
> So I think your additions are ab fab. However, if this is for the ticket about updating our sprint process, I think there's more to be added. One thing that stands out to me is there's no mention of grooming. Another is that we are doing 1 week sprints.

Added Sprint Grooming content, plus adjusted sprint length, start day, and added Definition of Ready as TODO

2021-06-25 00:34 UTC, kilbergr approved these changes
One missing word and a question, otherwise I think looking good!

2021-06-25 00:34 UTC, kilbergr commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
What's estimation of tickets? That's not pointing, is it?

2021-06-25 00:34 UTC, kilbergr commented on docs/how-we-work/README.md
> +     * 1: Well-understood and can be completed without requiring interaction between teams in less 1-2 work hours
```suggestion
     * 1: Well-understood and can be completed without requiring interaction between teams in less than 1-2 work hours
```
Sorry that's my b

2021-06-25 14:02 UTC, ssatagopan commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
Yes, pointing.

2021-06-25 18:36 UTC, kilbergr commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
We don't do pointing in grooming.

2021-06-25 18:36 UTC, kilbergr commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
We COULD split them, though.

2021-06-25 19:01 UTC, ssatagopan commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
hmm...so we only point during sprint planning? it helps provide visibility for the work in backlog if more tickets than just what's for next sprint are estimated.

2021-06-28 16:49 UTC, kilbergr commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
I've always done that way. Happy to try out this suggestion, but then we have the issue of everyone having to be at both grooming and sprint planning. Generally I like to keep grooming smaller. What do you think?

2021-06-28 17:30 UTC, ssatagopan commented on docs/how-we-work/README.md
> +* Estimation of tickets and splitting of tickets if needed
As discussed after standup, it's helpful for full team to be present at both meetings.

2021-06-28 17:31 UTC, merged